### ISSUE TITLE
[Bug] Multiple menu items active

### ISSUE THREAD

**Issue by andrewminion-luminfire** [maelstrom-cms/toolkit#7]
**Describe the bug**
When one menu item is a child of another, the parent is incorrectly highlighted when on the child page.

For example, given these two menu items:

1. Navigate to `/admin/pages` and just the first item will be highlighted, as expected.
![right](https://user-images.githubusercontent.com/47227887/75582176-a0bea480-5a30-11ea-9104-75b4f2c6af4b.png)

2. Navigate to `/admin/pages/create` and **both** items will be highlighted incorrectly.
![wrong](https://user-images.githubusercontent.com/47227887/75582183-a4eac200-5a30-11ea-8caa-0570c5d5001f.png)

```php
[
    [
        'type' => 'Link',
        'id' => 'pages-index',
        'label' => 'All Pages',
        'url' => '/admin/pages/',
    ],
    [
        'type' => 'Link',
        'id' => 'pages-create',
        'label' => 'New Page',
        'url' => '/admin/pages/create/',
    ],
]
```

**To Reproduce**
1. Create a sidebar with at least two elements, one of which has a URL that is a child of another
2. View the frontend
3. Click on the link for the child URL
4. Both child and parent menu items will be active.

**Expected behavior**
I expect that only the child element would be active.

**Screenshots**
See above.

**Additional context**
This may be an error with the Ant sidebar, but I haven’t been able to narrow it down yet to that or Maelstrom JS.

**Comment by OwenMelbz** [comment]
Hi,

This is sort of expected behaviour, albeit not desired in your case.

There automatic selection is done on “best efforts” rather than an exact science for most use cases it works out fine.

You’ve got 2 options really..

1. Use nested menu items rather than 2 top level links this should then highlight the right ones.

2. Explicitly tell the sidebar component which items you expect to be selected via your own custom logic.

Eg each sidebar item has a “selected” property which accepts true/false so you can control this yourself.

You can see an example here: https://github.com/maelstrom-cms/toolkit/issues/5#issuecomment-583856500

**Comment by OwenMelbz** [comment]
I will add some more examples and explanations into the docs though to make this more clear!

**Comment by andrewminion-luminfire** [comment]
Thanks…that makes sense.

I did have them nested originally but simplified it for the bug report: 
![Screen Shot 2020-02-28 at 14 00 02](https://user-images.githubusercontent.com/47227887/75583130-a6b58500-5a32-11ea-95c1-d0eb124c7915.png)

I’ll rework my menu structure a bit or explicitly tell it which should be selected; thanks!
